[build-system]
requires = ["scikit-build-core>=0.10", "pybind11"]
build-backend = "scikit_build_core.build"

[project]
name = "g2opy"
version = "2.1.0"
description="g2o: A General Framework for Graph Optimization"
readme = "README.md"
authors = [
  { name = "Rainer Kuemmerle", email = "rainer.kuemmerle@gmail.com" },
]
requires-python = ">=3.10"

[tool.scikit-build]
cmake.args = [
  "-DBUILD_SHARED_LIBS:=Off",
  "-DG2O_BUILD_PYTHON:=On",
  "-DG2O_BUILD_APPS:=Off",
  "-DG2O_BUILD_EXAMPLES:=Off",
  "-DG2O_USE_OPENGL:=Off"
]
cmake.build-type = "Debug"

wheel.packages = ["python/g2opy"]
messages.after-failure = "Build failed."
build.targets = ["g2opy"]
build.tool-args = ["-j4"]


[[tool.scikit-build.overrides]]
if.env.G2O_CACHE_BUILD = true
build-dir = "${env.PERSISTENT_BUILD_DIR}"
#build-dir = "${BUILD_PATH_ROOT}/tmp/g2opy"
#build-dir = "/tmp/g2opy"

[tool.cibuildwheel]
build-frontend = "build[uv]"

[tool.cibuildwheel.config-settings]
"cmake.build-type" = "Debug"


[tool.cibuildwheel.windows]
environment = { CFLAGS="/Zi", CXXFLAGS="/Zi", LDFLAGS="/DEBUG", CIBW_CMAKE_BUILD_ARGS="--config Debug" }

[tool.cibuildwheel.macos]
environment = { CFLAGS="-g", CXXFLAGS="-g" }
cmake.args = [
 "-DCMAKE_BUILD_TYPE=Debug"
]

[tool.cibuildwheel.linux]
before-build = "yum install -y eigen3-devel json-devel"
environment = { CFLAGS="-g", CXXFLAGS="-g" }
cmake.args = [
 "-DCMAKE_BUILD_TYPE=Debug"
]

[[tool.cibuildwheel.overrides]]
select = "*-musllinux*"
before-all = "apk add eigen"
# TODO install nlohmann-json

# windows
[[tool.scikit-build.overrides]]
if.platform-system = "^win32"
inherit.cmake.args = "append"
cmake.args = [
 "-DG2O_USE_CHOLMOD=ON",
 "-DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake",
 "-DCMAKE_BUILD_TYPE=Debug"
]
build.tool-args = ["-maxcpucount:16"]
cmake.build-type = "Debug"


[[tool.cibuildwheel.overrides]]
select = "*win*"
before-all = "vcpkg --triplet x64-windows install eigen3 nlohmann-json suitesparse"
